# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smartpizza}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080

# Azure OpenAI (matches @Value in AzureAIService.java)
azure.openai.api-key=8kBDlopqnIAen2jtDlgSaOytc0ml51AfsUgv0EkKtKMMzm5g0QHzJQQJ99CFACHYHv6XJ3w3AAAAACOGLZMX
azure.openai.endpoint=https://muthamizhfirstfoundaryp-resource.services.ai.azure.com/api/projects/muthamizhfirstfoundaryproj/openai/v1/responses

# Azure Maps (matches @Value in AzureMapsService.java)
azure.maps.key=1vPEGcYquJoaUwoiS6gEfhX7LJaiEuwfTjArxSeConb8df5tACXlJQQJ99CFACYeBjFPt68vAAAgAZMP3gnW 

# Razorpay (matches @Value in RazorpayService.java)
razorpay.key=rzp_test_T1CR3PCx1b8Xe9
razorpay.secret=FfYmaH6fpd6dqxkqVxocRuUf 
